DROP TABLE IF EXISTS favorite_foods CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS survey_user CASCADE;

CREATE TABLE survey_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    date_of_birth DATE NOT NULL,
    contact_number VARCHAR(20)
);

CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movies_rating INT NOT NULL CHECK (movies_rating BETWEEN 1 AND 5),
    radio_rating INT NOT NULL CHECK (radio_rating BETWEEN 1 AND 5),
    eat_out_rating INT NOT NULL CHECK (eat_out_rating BETWEEN 1 AND 5),
    tv_rating INT NOT NULL CHECK (tv_rating BETWEEN 1 AND 5),
    user_id BIGINT UNIQUE,
    FOREIGN KEY (user_id) REFERENCES survey_user(id) ON DELETE CASCADE
);

CREATE TABLE favorite_foods (
    response_id BIGINT,
    food VARCHAR(50) NOT NULL,
    PRIMARY KEY (response_id, food),
    FOREIGN KEY (response_id) REFERENCES ratings(id) ON DELETE CASCADE
);
